### PR TITLE
re-introduce jck compliant icon

### LINKED ISSUE #136: Website should give clear indication that Temurin releases pass the JCK
As per the title, the Adoptium website should give clear indicator to users that the Temurin releases have passed the applicable Java SE TCK.

### PR DESCRIPTION
**Pull request by gdams**
##### Checklist

- [x] `npm test` passes
- [ ] documentation is changed or added (if applicable)
- [ ] permission has been obtained to add new logo (if applicable)
- [x] contribution guidelines followed [here](https://github.com/adoptium/adoptium.net/blob/master/CONTRIBUTING.md)

Fixes: https://github.com/adoptium/adoptium.net/issues/136

### CODE REVIEW

**Comment by tellison** [comment]
Just thinking about the placement. I would expect this to appear next to the "LTS" icon in the table cell rather than the build id; and it clutters up the homepage download button.

**Comment by smlambert** [comment]
Can we also have a tick for AQA-verified?

**Review by tellison — APPROVED** [review]

**Review by karianna — APPROVED** [review]
LGTM

**Comment by gdams** [comment]
>Can we also have a tick for AQA-verified?

Yeah good idea, I'll open a new issue

**Pull request merged**
