### PR TITLE
Change default to OpenJDK 17

### PR DESCRIPTION
**Pull request by tellison**
Move default selection from OpenJDK 11 to latest LTS, OpenJDK 17

##### Checklist

- [x] `npm test` passes
- [ ] documentation is changed or added (if applicable)
- [ ] permission has been obtained to add new logo (if applicable)
- [x] contribution guidelines followed [here](https://github.com/adoptium/adoptium.net/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by tellison** [comment]
Leaving as draft until (i) most platforms released, and (ii) PMC approval given.

**Review by gdams — APPROVED** [review]

**Review by karianna — APPROVED** [review]
LGTM

**Comment by karianna** [comment]
Only AIX to go and then we can push this

**Comment by gdams** [comment]
PMC has approved this change

**Pull request merged**
