### PR TITLE
Add 18, remove 16

### PR DESCRIPTION
**Pull request by smlambert**
Signed-off-by: Shelley Lambert <slambert@gmail.com>

# Checklist

- [ ] `npm test` passes
- [ ] documentation is changed or added (if applicable)

### CODE REVIEW

**Review by sxa — CHANGES_REQUESTED** [review]
Line 243 needs to be changed too as the new table indicates that MacOS/aarch64 is not currently supported in JDK17 (because it wasn't in JDK16 which that column used to relate to)

**Comment by smlambert** [comment]
Thanks @sxa, updated!

**Review by tellison — APPROVED** [review]

**Review by karianna — APPROVED** [review]
LGTM

**Comment by smlambert** [comment]
@sxa - I've made the change you suggested, please confirm you approve and I'll merge this PR.

**Review by sxa — APPROVED** [review]

**Comment by gdams** [comment]
Wrong repo (sorry we need to archive this now). I did create a similar PR (https://github.com/adoptium/website-v2/pull/3940) which I merged today. I'd also be happy to remove JDK16 if we think it makes sense.

**Pull request closed without merging**
