### PR TITLE
switch to using Nunito Font from guidelines

### PR DESCRIPTION
**Pull request by gdams**
##### Checklist

- [x] `npm test` passes
- [ ] documentation is changed or added (if applicable)
- [ ] permission has been obtained to add new logo (if applicable)
- [x] contribution guidelines followed [here](https://github.com/adoptium/adoptium.net/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by hendrikebbers** [comment]
From my point of view we should use the **Nunito** font only for headlines. https://fonts.google.com/specimen/Nunito?query=Nunito#pairings defines some quite good combinations with other fonts. I like the combination with **Poppins** the most:

Bildschirmfoto 2021-04-15 um 16 00 35

**Comment by karianna** [comment]
Are we at an impasse here?

**Comment by hendrikebbers** [comment]
currently all text is rendered in Nunito. I would prefer to only use it for headlines. As mentioned the Poppins Font would be a good fit. @gdams how should we continue here?

**Comment by gdams** [comment]
@hendrikebbers @karianna updated PTAL

**Review by karianna — APPROVED** [review]
LGTM

**Pull request merged**
